### ISSUE TITLE
NewTUNIf set right destination

### ISSUE THREAD

**Issue by farss** [hujun-open/zouppp#1]
destination seems wrong?
zouppp0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1492
        inet 114.238.85.232  netmask 255.255.255.255  destination 114.238.85.232

**Comment by hujun-open** [comment]
zouppp doesn't set destination/peer address for its TUN interface because it is not needed for a point-to-point interface.
I guess the reason you see the destination address is same as interface address is due to behavior of certain kernel version (see below output on my linux box, there is no destination address at all)
and I think forwarding should still work

```
5: zouppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 20.20.4.1/32 scope global zouppp0
       valid_lft forever preferred_lft forever
    inet6 fe80::86bd:aed0:5797:e2d2/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
hj@pc-20:~$
hj@pc-20:~$ uname -a
Linux pc-20 5.12.8-051208-generic #202105281232 SMP Fri May 28 12:35:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by farss** [comment]
嗯 加上route 后确实可以用的. 有个问题请教下, 有没有办法让 tcp 直接走这个pppoe 连接?

**Comment by hujun-open** [comment]
> 
> 
> 嗯 加上route 后确实可以用的. 有个问题请教下, 有没有办法让 tcp 直接走这个pppoe 连接?

这已经不属于zouppp所负责的范畴了， 你的这个需求应该可以通过iptables（或nftable）的设置来实现
